# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('ubicacion', '0002_auto_20170912_1051'),
        ('activos_fijos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(blank=True, null=True)),
                ('numero_serial', models.CharField(blank=True, max_length=50, verbose_name='Número serial')),
                ('numero_placa', models.CharField(max_length=50, verbose_name='Número placa')),
                ('codigo_rfid', models.CharField(blank=True, max_length=50, verbose_name='Código RFID')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='ubicacion.CentroCostos')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='empleados.Empleado')),
            ],
            options={
                'verbose_name_plural': 'Activos fijos',
            },
        ),
    ]
