# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos_fijos', '0002_activofijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='tipo_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='activos_fijos.TipoActivo'),
        ),
    ]
