language: python
python:
- 3.6.2
install:
- pip install -r requirements.txt
script:
  - python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: mjDKbiwsiuoO7lUlO/vADNWm0J6grcOLHbUcw/hNjkfvApvx01E42qEnTHvXF2h8LIpIYgmNKeby3msU8mCrEan5MQpU72cniM2qbOiGdMXRV3N1nJ7B6qYJ3dxvV9Sm97HHm6L98X7ZjaxG7RhcJNr4XQxnsnkohqytqY30Rmee5nOSx0jqY85syMZmEIg9r8gv4akRwytJa/MzLu3gyKUuZt3MDOo0dwakJUqFC+/EbyehJi5UvCpxj4ILYskgJD8szSsD8nE4G8ZoPAfUgRH1gPf0Uy6rsJ5cnhqMkV3SWOaZ89KjNcmanMRVMRPlUjWWdINfg2fnB4d5ed60ALuhjhaZdrvz5VcOwFlkPQiPRaJ7NGyGBblrVAzm0wIVLW47z+ryYw6VQHXoW7bcoAwQRhN3rwfFqgYHCxv4zY8naV3I8hLq7WrQeP/AgjfuRWhiFOLWVL+YxXDUa1J4d/vhPng3jAtuARcUz+HioiEYXPvoewqHnFKF1YQ93d1qHXteT4Zdmc43NPo8t8p8nhF1+eaSDWqBpGDd8U8eR38/sY2LSNH1FM11Cox+d9lUNbj97AHqg5JWpl9atjToizFJRk9koho0YHEXCSvWmDteYkokjYrv6U2Mqwf6mpP0v/NwbW8AaCa7RnC2g1htCmECTaz+1di91QutiDPA+X8=
  app: prototipo-activos-fijos
  on:
    repo: difercamos/prototipo-activos-fijos
notifications:
  slack: 'diegofernan17:xoxp-240735564722-240218595617-242788652852-f07bd80bd1b2ff6a30f92756210d7578#activos_fijos'
